---
all:
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    
    # Initial username and password when first installing the OS on the servers
    initial_user: "root"
    initial_pass: "InitialSecretP@ssword!"

    automation_user: "automation"
    main_user: "server"

    ssh_keys:
      files:
        - "~/.ssh/id_rsa.pub"
      strings:
        - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIG+rdql+syD1t4jW8G1VrZkLCq1WfE1lL6R0wcAGFr29"
    
    update_packages: true

  hosts:
    node1:
      ansible_host: vps-test2.an-men.de
