---
all:
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    
    ############################################################################
    ############################### SETUP_USERS ################################
    ############################################################################
    # Initial username and password when first installing the OS on the servers.
    # This user will not be used, if the automation user exists.
    initial_user: "root"
    initial_pass: "InitialP@ssword!"

    # The admin user can be used by the server admin or as a backup root user.
    admin_user:
      name: server
      ssh_keys:
        files:
          - "~/.ssh/id_rsa.pub"
        strings:
          - "ssh-ed25519 KEY_1"
          - "ssh-ed25519 KEY_2"
    
    # The automation user is used by Ansible and can also be used by other
    # automation tasks. This user also has root access.
    # Make sure to add the public key of the machine executing (this) Ansible
    # playbook.
    automation_user:
      name: "automation"
      ssh_keys:
        files:
          - "~/.ssh/id_rsa.pub"
        strings:
    
    # Main users
    # Want to be sudo? ONLY set the is_sudoer variable to true (don't add the
    # sudoers group manually).
    users:
      - name: user1
        public_key: "ssh-ed25519 KEY"
        is_sudoer: true
        groups:
          - "group_1"
          - "group_2"
      - name: user2
        public_key: "ssh-ed25519 KEY"
        is_sudoer: false
        groups:
    
    ############################################################################
    ################# SETUP_PACKAGES_APT && SETUP_PACKAGES_DNF #################
    ############################################################################
    packages:
      - nano
      - micro
    update_packages: true

    ############################################################################
    ############################## INSTALL_GOLAN ###############################
    ############################################################################
    go_version: 1.20.3

  hosts:
    node1:
      ansible_host: server1.example.com
    
    node2:
      ansible_host: server2.example.com
